### ISSUE TITLE
C-c C-f conflicts with AucTeX

### ISSUE THREAD

**Issue by rmcd1024** [Malabarba/latex-extra#14]
tex.el defines C-c C-f as TeX-font, so enabling latex-extra clobbers a (very useful IMO) feature in AucTeX.

**Comment by Malabarba** [comment]
Hey there. 
The keymap is moved under C-c f, and there's an option to disable this. It's all in the readme. ;-)

**Comment by rmcd1024** [comment]
Thanks, believe it or not, I did read the readme, I just missed that! Is there a reason not to keep the AucTeX font mappings as they are, and use C-c f for the move to section command?

**Comment by Malabarba** [comment]
The C-c C-f mapping was chosen to match the keybinds that org-mode uses for navigation. Org-mode is what inspired this feature, so I wanted to imitate the bindings.

(And the fact that originally I didn't know about auctex's font-map might have something to do with it :-)).

**Comment by rmcd1024** [comment]
Thanks!
