### ISSUE TITLE
Bibliography with BibLaTeX/Biber

### ISSUE THREAD

**Issue by elandx** [Malabarba/latex-extra#19]
Thanks for the package, it works great.  But I have such issue with bibliography: the package always use BibTeX, even if BibLaTeX is specified in preamble with option "biber", so bibliography is not compiled properly.  Thanks in advance :)

**Comment by Malabarba** [comment]
Latex-extra  uses whichever command would

**Comment by Malabarba** [comment]
Latex-extra simply runs whichever command would be offered by AucTex when you type `C-c C-c`. Maybe there's a way to configure AucTex to use Biblatex instead of bibtex?

**Comment by elandx** [comment]
Of course, You're right, AucTeX (C-c C-c) offers the Biber as a choice. If I could configure AucTeX to always use BibLaTeX/Biber instead of BibTeX, I would have try it before write to You. Unfortunately Google is not too helpful on the subject.  Thanks.
