### ISSUE TITLE
clean-fill-indent-environment does not respect sentence-end-double-space

### ISSUE THREAD

**Issue by moble** [Malabarba/latex-extra#21]
The `latex-extra` provided command `latex/clean-fill-indent-environment` does not seem to respect the variable `sentence-end-double-space`.  I have the latter set to `t`, which means that filling should leave two spaces after the end of a sentence.  However, when I run this command on text that already has those spaces, they disappear.  I [am not alone](http://stevelosh.com/blog/2012/10/why-i-two-space/) in disliking this behavior, but more importantly it breaks other functions I have that assume that double space to figure out what constitutes a sentence end as opposed to an abbreviation.

**Comment by Malabarba** [comment]
Yeah, that's a bug. It removes extra whitespace to fix indentation and cleanup equations, breaking sentence ends was not intentional.

**Comment by moble** [comment]
Seems to do the job for me.  Thanks!

**Comment by Malabarba** [comment]
Great!
