### ISSUE TITLE
latex-extra shadows AUCTeX's own `TeX-command-run-all`

### ISSUE THREAD

**Issue by duetosymmetry** [Malabarba/latex-extra#26]
As of AUCTeX version 11.89 (Nov. 2015), there is already a package command on C-c C-a which executes `TeX-command-run-all`. latex-extra should test for the AUCTeX version number, and should only install C-c C-a if the version number is less than 11.89.

**Comment by Malabarba** [comment]
That's great to know. It would be even better (and easier) to just check if the command is fboundp before defining the function. Would you like to try a PR?

**Comment by duetosymmetry** [comment]
I don't have the elisp skills for that. The extent of my abilities would be to duplicate the code for, say, `latex/override-fill-map` to say `latex/override-run-all-map`.

**Comment by Malabarba** [comment]
That won't be necessary. It's just a matter of wrapping the defun in a `(unless (fboundp 'TeX...)...)`. 

I'll try to do it when I get a chance.

**Comment by Malabarba** [comment]
Fixed.
