### ISSUE TITLE
'tex-buf.el' is merged into 'tex.el" with auctex 13

### ISSUE THREAD

**Issue by berhoel** [Malabarba/latex-extra#35]

**Comment by mandarm** [comment]
I'm hoping commenting out `(require 'tex-buf)` on line 133 will solve the problem. Nice if this change could be made in the package itself. Thanks!

**Comment by Malabarba** [comment]
Thanks for for the notice. Could someone make a pr with the change?
I haven't been using auctex in a while now, so it would be a bit of a hassle to setup and test a fix.

**Comment by tarsius** [comment]
@berhoel opened a pr right after opening this issue: #36.

**Comment by Malabarba** [comment]
True. Somehow I missed that on the notifications.
